name: build

on:
  push:
    branches: [ "feature/actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Google Chrome # Using shell script to install Google Chrome
        run: |
          chmod +x ./.github/scripts/InstallChrome.sh
          ./scripts/InstallChrome.sh 

      - name: Install Chrome Driver # Using shell script to install Chrome Driver
        run: |
          chmod +x ./.github/scripts/downloadDriver.sh
          ./scripts/downloadDriver.sh 

#      - uses: browser-actions/setup-chrome@latest
#      - run: chrome --version

      - name: Build with Maven
        run: mvn -B clean test