name: test

on:
  push:
    branches: [ "feature/actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Deploy
        uses: ./.github/template/deploy

      - name: Test
        run: mvn clean install -DactiveProfile=headless-github