name: test

on:
  push:
    branches: [ "feature/actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: ./.github/template/deploy

      - name: Test
        run: mvn clean install -DactiveProfile=headless-github